Algoritmo "Contar de 10 a 0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/11/2020
Var
// Seção de Declarações das variáveis
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
i <- 10
enquanto (i >= 0) faca
   escreval (i)
   i <- i - 1
fimenquanto

Fimalgoritmo